# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /djangoreactproj

# Copy the requirements file into the container
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /usr/src/app
COPY . /djangoreactproj

# Make port 8000 available to the world outside this container
EXPOSE 8000


# Define environment variable
ENV DJANGO_SETTINGS_MODULE=djangoreactproj.settings

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

