# Generated by Django 4.2.11 on 2024-03-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="recordtype",
            name="type",
            field=models.CharField(unique=True),
        ),
    ]
