# Generated by Django 4.2.11 on 2024-03-13 19:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_manager", "0002_alter_platform_name_alter_recordtype_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="filename",
        ),
        migrations.AddField(
            model_name="post",
            name="platform_specific_reference",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="record",
            name="author",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="record",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="record",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="suffix",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="annotation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), blank=True, size=None
            ),
        ),
    ]
