# Generated by Django 4.2.11 on 2024-03-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db_manager", "0003_remove_record_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="source_platform",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="db_manager.platform",
            ),
        ),
    ]
